controllers/HelpController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\ContactForm;

use yii\filters\AccessControl;
use common\models\User;
use common\components\AccessRule;

class HelpController extends \yii\web\Controller
{

    public $defaultAction = 'start';

    public function behaviors(){
        return [
            'access' => [
                'class' => AccessControl::className(),
                'ruleConfig' => [
                    'class' => AccessRule::className(),
                ],
                'rules' => [
                    [
                        'actions' => ['about', 'contact', 'payments', 'start', 'terms', 'finishtutorial', 'privacy'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['about', 'contact', 'start', 'terms', 'privacy'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
        ];
    }

    public function actionAbout($tutotrial = false)
    {
        return $this->render('about',['tutotrial' => $tutotrial]);
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact($tutotrial = false)
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
                'tutotrial' => $tutotrial,
            ]);
        }
    }

    public function actionPayments()
    {
        return $this->render('payments');
    }

    public function actionStart($tutotrial = false)
    {
        return $this->render('start', ['tutotrial' => $tutotrial]);
    }

    public function actionTerms()
    {
        return $this->render('terms');
    }

    public function actionPrivacy()
    {
        return $this->render('privacy');
    }

    public function actionFinishtutorial()
    {
        $model = User::findOne(Yii::$app->user->identity->id);
        $model->times_logged = 1;
        $model->save();

        return $this->redirect(['subscription/index']);
    }

}

views/help/_menu.php
<?php
// use yii\bootstrap\Nav;
use yii\widgets\Menu;
use yii\helpers\Url;

$menuItems = [];

$menuItems[] = ['label' => 'Getting started', 'url' => ['help/start']] ;
$menuItems[] = ['label' => 'About TRodds', 'url' => ['help/about']] ;
// $menuItems[] = ['label' => 'Payments', 'url' => ['help/payments']] ;
//$menuItems[] = ['label' => 'Terms, privacy Disclaimer', 'url' => ['help/terms']] ;
$menuItems[] = ['label' => 'Contact us', 'url' => ['help/contact']] ;
    
$checkUrl = 'help/'.Yii::$app->controller->action->id;

/*foreach($menuItems as &$menuItem) {
    if($menuItem['url'][0] == $checkUrl) {
        $menuItem['template'] = '<a class="main_menu_link active" href="{url}">{label}</a>';
    }
}*/

?>
<?php echo Menu::widget([
        'options' => [
            'class' => 'main_menu_list'
        ],
        'itemOptions' => [
            'class' => 'main_menu_item'
        ],
        'linkTemplate' => '<a class="main_menu_link" href="{url}">{label}</a>',
        'items' => $menuItems,
    ]);
?>

views/help/_menu_help.php
<?php
// use yii\bootstrap\Nav;
use yii\widgets\Menu;
use yii\helpers\Url;

$menuItems = [];

$menuItems[] = ['label' => 'Terms of Use', 'url' => ['help/terms']] ;
$menuItems[] = ['label' => 'Privacy Policy', 'url' => ['help/privacy']] ;
    
$checkUrl = 'help/'.Yii::$app->controller->action->id;

?>
<?php echo Menu::widget([
        'options' => [
            'class' => 'main_menu_list'
        ],
        'itemOptions' => [
            'class' => 'main_menu_item'
        ],
        'linkTemplate' => '<a class="main_menu_link" href="{url}">{label}</a>',
        'items' => $menuItems,
    ]);
?>

views/help/contact.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

/* @var $this yii\web\View */

$this->title = 'Contact Us';
$this->params['breadcrumbs'][] = $this->title;
?>
  <main>

    <div class="main_menu clearfix width_container">
      <div class="container_list">
        <?= $this->render('_menu') ?>
      </div>
    </div>
    <div class="contact_main">
      <div class="contact_form_info row">
        <div class="contact_info col-10 col-md-4 col-sm-4 contact_info__help">
          <p>
            Feel free to send us your queries at any time and our support team will respond in the shortest time possible. Please fill the form or send us email to support@trodds.com.
          </p>
          <h2>Thank you for contacting us!</h2>
        </div>
        <div class="contact_form col-10 col-md-4 col-sm-4 help_contact_us">
          <p class="contact_form_title">Contact us</p>
            <?php $form = ActiveForm::begin([
                    'id' => 'contact-form',
                    'options' => [
                        'class' => 'form_contact'
                    ],
                    
                    'errorCssClass' => 'has-danger',
                    'fieldConfig' => [
                        'hintOptions' => [
                            'class' => 'hidden-xs-up form-control-feedback'
                        ],
                        'errorOptions' => [
                            'class' => 'hidden-xs-up form-control-feedback'
                        ]
                    ]
                ]); 
            ?>
            <p class="form_contact_name">Name</p>
            <?= $form->field($model, 'first_name')->textInput(['autofocus' => true, 'placeholder' => 'My name'])->label(false); ?>
            <p class="form_contact_email">Email<span id="true"></span><span id="false"></span></p>
            <?= $form->field($model, 'email')->textInput()->input('text', ['placeholder' => 'email@user.com', ''])->label(false); ?>
            <p class="form_contact_subject">Subject</p>
            <?= $form->field($model, 'subject')->textInput(['placeholder' => ''])->label(false); ?>
            <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                'options' => [
                    'placeholder' => 'Captcha code:',
                    'class' => 'form-control'
                ],
                'template' => '<p class="form_contact_capcha">Captcha code</p><div class="input-group">{input}<span class="input-group-addon" style="padding:0;">{image}</span></div>',
            ])->label(false) ?>
            <p class="form_contact_message">Your message</p>
            <p><?= $form->field($model, 'body', ['template' => '{input}{error}'])->textArea()?></p>
            <input type="submit" name="" value="Send">
          <?php ActiveForm::end(); ?>
        </div>
      </div>
    </div>
  </main>

views/help/payments.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'Payments';
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="section section-image section-faded" style="background-image:url(<?= Url::to('@web/img/banner2.jpg') ?>); background-position:center center;">
    <div class="container">
        <h2 class="text-xs-center"><?= $this->title ?></h2>
    </div>
</section>
<section class="section">
    <div class="container">
        <div id="tabs-container">
            <?= $this->render('_menu') ?>
            <div class="card tab-content" style="border-top:0;border-top-left-radius: 0;border-top-right-radius: 0;">
                <div id="tab-3" class="tab-pane card-block active">
                    <h3 class="mb-2">Payments</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur tempor incididunt. Lorem ipsum dolor sit amet, consectetur
                        adipiscing elit, sed do eiusmod tempor incididunt.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur tempor incididunt. Lorem ipsum dolor sit amet, consectetur
                        adipiscing elit, sed do eiusmod tempor incididunt.</p>
                    <div class="bookies mt-2">
                        <div class="row">
                            <div class="col-sm-6 col-lg-4">
                                <div class="card text-xs-center mb-2">
                                    <img class="card-img-top" src="/img/bookie-icon.png" alt="company">
                                    <div class="card-block">
                                        <h4 class="card-title">Company Name</h4>
                                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur tempor incididunt. Lorem ipsum dolor
                                            sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                                        <a href="#" class="btn btn-success">Open Account</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-lg-4">
                                <div class="card text-xs-center mb-2">
                                    <img class="card-img-top" src="/img/bookie-icon.png" alt="company">
                                    <div class="card-block">
                                        <h4 class="card-title">Company Name</h4>
                                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur tempor incididunt. Lorem ipsum dolor
                                            sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                                        <a href="#" class="btn btn-success">Open Account</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-lg-4">
                                <div class="card text-xs-center mb-2">
                                    <img class="card-img-top" src="/img/bookie-icon.png" alt="company">
                                    <div class="card-block">
                                        <h4 class="card-title">Company Name</h4>
                                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur tempor incididunt. Lorem ipsum dolor
                                            sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                                        <a href="#" class="btn btn-success">Open Account</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

views/help/privacy.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use common\widgets\Alert;

/* @var $this yii\web\View */

$this->title = 'Terms & Privacy';
$this->params['breadcrumbs'][] = $this->title;
?>
  <main>
    <div class="container clearfix">
      <div class="main_menu clearfix width_container">
        <div class="container_list">
          <ul class="main_menu_list">
			<?= $this->render('_menu_help') ?>
          </ul>
        </div>
      </div>
      <div class="help_terms">
        <div class="terms_info">
          <div class="terms_info_title">
            <h2>Privacy Policy</h2>
            <p class="policy_number_indent">
              <span></span> <i>The following privacy policy shows the manner</i> in which Top Rated Odds (the company) collects, mantaines, uses, and discloses information collected from the company clients (the user) of www.trodds.com website (the site).
              This privacy policy applies to this site and any other products and services offered by the company.
            </p>
            <p class="policy_number_indent">
              <span>1.</span> <i>Collection of personal and non personal information</i>
            </p>
            <p>
              <span>A.</span>&nbsp; We may collect personal identification from users in various ways, including but not limited to, when user visit the website, registers, fill out a forms, and in connection with other services, activities, features
              or resources we offer to our users in the company website. We collect such information only if users voluntarily submits this type of information, users may be asked for for identification purposes some of their personal information (name,
              email), user can refuse to supply such personal information if chooses, expect it may them from engaging certain parts of the website, products, services, resources and features. WE DON’T COLLECT ANY PAYMENT INFORMATION FROM OUR USERS.
            </p>
            <p>
              <span>B.</span>&nbsp; The company may collect non personal information about users whenever the user visits our website, information such a browser name, operational system, type of computer and technical information of the user means connection
              to our webiste and other similar information
            </p>
            <p class="policy_number_indent">
              <span>2.</span> <i>Web browser cookies & usage of information</i>
            </p>
            <p>
              <span>A.</span>&nbsp; The company uses cookies, to understand and save user preferences for future visits and compile overall data about the site including site traffic and interaction to improve the site experience and tools for future
              visits. The company may contract with any 3rd party to help the website in better understanding of our visitors, these 3rd party services are not permitted to collect user personal data on the company's behalf expect to conduct and help
              the company by improving our business.
            </p>
            <p>
              <span>B.</span>&nbsp; The email address the user provides will be used only to improve user personalized experience, to respond to user queries in order to improve the company website customer support, to send user after opt-in daily/weekly/monthly
              updates regarding the company products, services and/or features in order to improve the quality of such services, features and/or products.
            </p>
            <p>
              <span class="policy_number_indent">3.</span> <i>Protection of information of information</i> The website adopts necessary techniques for collected information, storage, processing to and any security measures in order to protect the data
              from unwanted and unauthorized access, disclosure and/or access to the user personal information, email, password, and any other personal information stored on the company website.
            </p>
            <p class="policy_number_indent">
              <span>4.</span> <i>Sharing the user personal information</i> the company isn't and won’t sell, trade or rent user's personal information to any other 3rd party company, we may share overall demographic information not associated with an
              individual user regarding visitors and/or users with the company business partners, affiliates and/or other 3rd party partners.
            </p>
            <p class="policy_number_indent">
              <span>5.</span> <i>3rd party website.</i> User may find advertisements or other content that linked to 3rd party website on the company's website, includes but not limited to partners, suppliers, advertisers, sponsors and other 3rd parties.
              The company is not controls the content that is on these 3rd party websites in any way or manner and are not responsible for the 3rd party websites practises employed there. These site and services may have their own privacy policies, browsing
              and interaction on any other 3rd party websites, including websites that are linked to the company's site is subjected to the 3rd party website's own terms and policies
            </p>
            <p class="policy_number_indent">
              <span>6.</span> <i>Changes to this privacy policy & your acceptance to them</i> the company may update this privacy policy from time to time, and will publish this changes on the website, it the user solely responsibility to check for any
              updates regarding the privacy policy. By using the company's website the user signifies the agreement of the privacy policy and terms of service, if you don't agree to any part of the privacy policy please dont user the company website or
              any additional products, services and features. You continued usage of the website even following after some modification in the privacy policy and terms of user, is deemed as the user acceptance for them. If you have any questions regarding
              the usage of the website, terminology of the privacy policy and/or terms of use please don't hesitate to contact us at support@trodds.com
            </p>
          </div>
        </div>
      </div>
    </div>
  </main>